services:
  frontend:
    build: ./frontend
    environment:
      - SIGNALING_SERVER_URL=${SIGNALING_SERVER_URL}
    ports:
      - "13000:80"

  signaling-server:
    build: ./server
    environment:
      - CLIENT_URL=${CLIENT_URL}
    ports:
      - "18000:8000"
